spring:
  application:
    name: BCardManagingSys
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres1
    username: postgres
    password: hypadJ

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: false
    default-schema: "bank_card_schema"

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

logging:
  level:
    com:
      gtr3base:
        bankcards:
          security: TRACE

bankcards:
  jwt:
    secret: "3ecf5388e220da9e0f919485deb676d8bee3aec046a779353b463418511ee622"
    expires-in-ms: 360000


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /docs/openapi.yaml

server:
  port: 8080